# This is the network config written for GB linux course
network:
  version: 2
  ethernets:
    ens160:
      addresses: [172.16.8.128/24]
      routes:
        - to: 0.0.0.0/0
          via: 172.16.8.0
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
      dhcp4: no
